<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AdminPIMLeaveTimeRecruitmentMy InfoPerf_b2e910</name>
   <tag></tag>
   <elementGuidId>58519aab-c205-46d2-a93a-a3800fdcc473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.oxd-layout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9fb2031c-81f9-4adf-95c7-b1b171b1c380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-layout</value>
      <webElementGuid>e8e5634b-6bdd-4a4f-b8b4-b1e165aa33b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AdminPIMLeaveTimeRecruitmentMy InfoPerformanceDashboardDirectoryMaintenanceBuzzPIMPaul CollingsConfiguration Employee ListAdd EmployeeReportsUpdate PasswordUsernameAdminCurrent PasswordVery Weak PasswordShould have at least 8 charactersFor a strong password, please use a hard to guess combination of text with upper and lower case characters, symbols and numbersConfirm PasswordRequired * Required Cancel  Save OrangeHRM OS 5.2© 2005 - 2022 OrangeHRM, Inc. All rights reserved.</value>
      <webElementGuid>b241159c-3c2a-4622-8d70-431d6f247cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]</value>
      <webElementGuid>c728e1e0-c4ad-41d7-abc3-12626eafdede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div</value>
      <webElementGuid>84b280be-1cfe-47cc-8aca-296a56692a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>c59f3d54-6bd8-4b66-bbd3-f4b6d569d469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AdminPIMLeaveTimeRecruitmentMy InfoPerformanceDashboardDirectoryMaintenanceBuzzPIMPaul CollingsConfiguration Employee ListAdd EmployeeReportsUpdate PasswordUsernameAdminCurrent PasswordVery Weak PasswordShould have at least 8 charactersFor a strong password, please use a hard to guess combination of text with upper and lower case characters, symbols and numbersConfirm PasswordRequired * Required Cancel  Save OrangeHRM OS 5.2© 2005 - 2022 OrangeHRM, Inc. All rights reserved.' or . = 'AdminPIMLeaveTimeRecruitmentMy InfoPerformanceDashboardDirectoryMaintenanceBuzzPIMPaul CollingsConfiguration Employee ListAdd EmployeeReportsUpdate PasswordUsernameAdminCurrent PasswordVery Weak PasswordShould have at least 8 charactersFor a strong password, please use a hard to guess combination of text with upper and lower case characters, symbols and numbersConfirm PasswordRequired * Required Cancel  Save OrangeHRM OS 5.2© 2005 - 2022 OrangeHRM, Inc. All rights reserved.')]</value>
      <webElementGuid>bcf80573-e70b-4248-83f2-c3de283a6175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
